services:
  authentication-api:
    build:
      context: ./services/authentication-api
    ports:
      - "8084:8084"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8084
      - MongoDB__ConnectionString=mongodb://mongodb:27017
    depends_on:
      - mongodb
    networks:
      - feigram-net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - feigram-net

volumes:
  mongo_data:

networks:
  feigram-net:
    driver: bridge
