version: '3.8'

services:
  follow-api:
    build:
      context: ./services/follow-api
    ports:
      - "8087:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=admin123
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/admin123
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
