version: '3.8'

services:
  # --- Authentication API ---
  authentication-api:
    platform: linux/amd64
    build:
      context: ./services/authentication-api
    ports:
      - "8084:8084"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8084
      - MongoDB__ConnectionString=mongodb://mongodb:27017
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - feigram-net

  # --- MongoDB ---
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - feigram-net

  # --- Profile API ---
  profile-api:
    platform: linux/amd64
    build:
      context: ./services/profile-api
    ports:
      - "8088:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=profiledb;Username=postgres;Password=admin123
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - feigram-net

  # --- Follow API ---
  follow-api:
    build:
      context: ./services/follow-api
    ports:
      - "8087:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=admin123
    depends_on:
      - neo4j
      - rabbitmq
    networks:
      - feigram-net

  # --- RabbitMQ ---
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - feigram-net

  # --- Neo4j ---
  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/admin123
    volumes:
      - neo4j_data:/data
    networks:
      - feigram-net

  # --- PostgreSQL ---
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: profiledb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - profile_data:/var/lib/postgresql/data
    networks:
      - feigram-net

# --- Volúmenes ---
volumes:
  mongo_data:
  neo4j_data:
  profile_data:

# --- Red compartida ---
networks:
  feigram-net:
    driver: bridge
