services:
  nginx:
    image: nginx:latest
    container_name: feigram-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./clients/feigram-web/build:/usr/share/nginx/html:ro
    depends_on:
      - post-api
      - profile-api
      - likes-api
      - comments-api
      - authentication-api
      - feed-api
      - follow-api
      - chart-api
      - message-api
    networks:
      - feinet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - feinet

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - feinet
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: profiledb
    ports:
      - "5432:5432"
    networks:
      - feinet
    volumes:
      - profile_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/admin123
    networks:
      - feinet
    volumes:
      - neo4j_data:/data

  post-api:
    build:
      context: ./services/post-api
      dockerfile: Dockerfile
    container_name: post-api
    # ports:
    #   - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DBNAME=feigram
    networks:
      - feinet
    depends_on:
      - mongo
      - rabbitmq

  profile-api:
    build:
      context: ./services/profile-api
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: profile-api
    # ports:
    #   - "8081:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=profiledb;Username=postgres;Password=admin123
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - feinet

  likes-api:
    build:
      context: ./services/likes-api
      dockerfile: Dockerfile
    container_name: likes-api
    # ports:
    #   - "8082:8082"
    environment:
      - MongoDb__ConnectionString=mongodb://mongo:27017
      - MongoDb__DatabaseName=feigram
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - feinet

  comments-api:
    build:
      context: ./services/comments-api
      dockerfile: Dockerfile
    container_name: comments-api
    # ports:
    #   - "8083:8083"
    environment:  
      - MongoDb__ConnectionString=mongodb://mongo:27017
      - MongoDb__DatabaseName=feigram
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - feinet

  authentication-api:
    platform: linux/amd64
    build:
      context: ./services/authentication-api
    container_name: authentication-api
    # ports:
    #   - "8084:8084"
    environment:
      - MongoDB__ConnectionString=mongodb://mongo:27017
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - feinet

  feed-api:
    build:
      context: ./services/feed-api
    container_name: feed-api
    # ports:
    #   - "8085:8085"
    depends_on:
      - rabbitmq
    networks:
      - feinet

  follow-api:
    build:
      context: ./services/follow-api
      dockerfile: Dockerfile
    container_name: follow-api
    # ports:
    #   - "8086:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=admin123
    depends_on:
      - neo4j
      - rabbitmq
    networks:
      - feinet

  chart-api:
    build:
      context: ./services/chart-api
      dockerfile: Dockerfile
    container_name: chart-api
    # ports:
    #   - "8087:8087"
    depends_on:
      - rabbitmq
    networks:
      - feinet

  message-api:
    build:
      context: ./services/message-api
      dockerfile: Dockerfile
    container_name: message-api
    # ports:
    #   - "8088:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - JWT_SECRET_KEY=V7hX!3tZq@wL9rM8k#1P&2oH8nD2u7Vb9G5wI8sL5kYwJ0tR0bB4cX9Q3fTg5
      - JWT_ISSUER=authentication-api
      - JWT_AUDIENCE=FeigramClient
    depends_on:
      - mongo
    networks:
      - feinet

  ads-api:
    build:
      context: ./services/ads-api
      dockerfile: Dockerfile
    container_name: ads-api
    # ports:
    #   - "9092:9092"
    environment:
      - PORT=9092
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB=adsdb
    depends_on:
      - mongo
    networks:
      - feinet

  feigram-web:
    build:
      context: ./clients/feigram-web
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: feigram-web
    # ports:
    #   - "8089:8089"
    networks:
      - feinet

networks:
  feinet:

volumes:
  mongo_data:
  profile_data:
  neo4j_data:
  nginx_data:
  nginx_letsencrypt:
