services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    ports:
      - "9090:80"     # Acceso público por HTTP (puerto personalizado)
      - "4443:443"    # HTTPS personalizado si no quieres 443
      - "8181:81"     # Admin Panel de NPM
    networks:
      - feinet
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - feinet

  mongo:
    image: mongo:6
    container_name: mongo
    networks:
      - feinet
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: profiledb
    ports:
      - "5432:5432"
    networks:
      - feinet
    volumes:
      - profile_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/admin123
    networks:
      - feinet
    volumes:
      - neo4j_data:/data

  post-api:
    build:
      context: ./services/post-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - feinet
    depends_on:
      - mongo
      - rabbitmq

  profile-api:
    build:
      context: ./services/profile-api
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8081:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=profiledb;Username=postgres;Password=admin123
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - feinet

  likes-api:
    build:
      context: ./services/likes-api
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - MongoDb__ConnectionString=mongodb://mongo:27017
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - feinet

  comments-api:
    build:
      context: ./services/comments-api
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - MongoDb__ConnectionString=mongodb://mongo:27017
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - feinet

  authentication-api:
    build:
      context: ./services/authentication-api
    ports:
      - "8084:8084"
    environment:
      - MongoDB__ConnectionString=mongodb://mongo:27017
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - feinet

  feed-api:
    build:
      context: ./services/feed-api
    ports:
      - "8085:8085"
    depends_on:
      - rabbitmq
    networks:
      - feinet

  follow-api:
    build:
      context: ./services/follow-api
      dockerfile: Dockerfile
    ports:
      - "8086:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=admin123
    depends_on:
      - neo4j
      - rabbitmq
    networks:
      - feinet

  chart-api:
    build:
      context: ./services/chart-api
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    depends_on:
      - rabbitmq
    networks:
      - feinet

  message-api:
    build:
      context: ./services/message-api
      dockerfile: Dockerfile
    ports:
      - "8088:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - JWT_SECRET_KEY=V7hX!3tZq@wL9rM8k#1P&2oH8nD2u7Vb9G5wI8sL5kYwJ0tR0bB4cX9Q3fTg5
      - JWT_ISSUER=authentication-api
      - JWT_AUDIENCE=FeigramClient
    depends_on:
      - mongo
    networks:
      - feinet

  # feigram-web:
  #   build:
  #     context: ./clients/feigram-web
  #     dockerfile: ../Dockerfile
  #   ports:
  #     - "8089:8089"
  #   networks:
  #     - feinet

networks:
  feinet:

volumes:
  mongo_data:
  profile_data:
  neo4j_data:
  nginx_data:
  nginx_letsencrypt:
