version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  likes-api:
    build:
      context: ./services/likes-api/src/likes-api

    ports:
      - "8088:8088"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MongoDb__ConnectionString: mongodb://mongo:27017
    depends_on:
      - mongo

volumes:
  mongo_data:
