version: '3.8'

services:
  post-api:
    build:
      context: ./services/post-api
    ports:
      - "8088:8000"
    env_file:
      - ./services/post-api/.env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DBNAME=feigram
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
