version: '3.8'

services:
  profile-api:
    platform: linux/amd64
    build:
      context: ./services/profile-api
    ports:
      - "8088:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=profiledb;Username=postgres;Password=admin123
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - feigram-net

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: profiledb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - profile_data:/var/lib/postgresql/data
    networks:
      - feigram-net

  authentication-api:
    platform: linux/amd64
    build:
      context: ./services/authentication-api
    ports:
      - "8084:8084"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8084
      - MongoDB__ConnectionString=mongodb://mongodb:27017
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - feigram-net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - feigram-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - feigram-net

volumes:
  profile_data:
  mongo_data:

networks:
  feigram-net:
    driver: bridge
