apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments-api
  template:
    metadata:
      labels:
        app: comments-api
    spec:
      containers:
      - name: comments-api
        image: your-docker-registry/comments-api:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: comments-api
spec:
  selector:
    app: comments-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
